from __future__ import annotations

from torchvision.models import ResNet50_Weights

DEFAULT_WEIGHTS = ResNet50_Weights.DEFAULT
TOP_K = 5
CAM_OVERLAY_ALPHA = 0.45
CAM_SCORE_TYPE_DEFAULT = "logit"

IG_STEPS_DEFAULT = 50
IG_INTERNAL_BATCH_SIZE_DEFAULT = 16
IG_BASELINE_BLUR_RADIUS_DEFAULT = 4

OCC_PATCH_SIZE_DEFAULT = 24
OCC_STRIDE_DEFAULT = 12
OCC_BASELINE_BLUR_RADIUS_DEFAULT = 4

LIME_N_SAMPLES_DEFAULT = 600
LIME_PERTURBATIONS_PER_EVAL_DEFAULT = 64
LIME_N_SEGMENTS_DEFAULT = 70
LIME_COMPACTNESS_DEFAULT = 10.0
LIME_SIGMA_DEFAULT = 1.0
LIME_BASELINE_BLUR_RADIUS_DEFAULT = 2
LIME_RANDOM_SEED_DEFAULT = 0
