from __future__ import annotations

from torchvision.models import ResNet50_Weights

DEFAULT_WEIGHTS = ResNet50_Weights.DEFAULT
TOP_K = 5
CAM_OVERLAY_ALPHA = 0.45
CAM_SCORE_TYPE_DEFAULT = "logit"
MAX_UI_IMAGE_SIDE = 1024
ANALYSIS_CACHE_TTL_SECONDS = 600
ANALYSIS_CACHE_MAX_ENTRIES = 3

IG_STEPS_DEFAULT = 24
IG_INTERNAL_BATCH_SIZE_DEFAULT = 16
IG_BASELINE_BLUR_RADIUS_DEFAULT = 4

OCC_PATCH_SIZE_DEFAULT = 32
OCC_STRIDE_DEFAULT = 32
OCC_BASELINE_BLUR_RADIUS_DEFAULT = 4

LIME_N_SAMPLES_DEFAULT = 120
LIME_PERTURBATIONS_PER_EVAL_DEFAULT = 32
LIME_N_SEGMENTS_DEFAULT = 40
LIME_COMPACTNESS_DEFAULT = 10.0
LIME_SIGMA_DEFAULT = 1.0
LIME_BASELINE_BLUR_RADIUS_DEFAULT = 2
LIME_RANDOM_SEED_DEFAULT = 0

METRICS_ENABLED_DEFAULT = True
METRICS_ROBUSTNESS_ENABLED_DEFAULT = False
METRICS_RANDOM_SEED_DEFAULT = 0
METRICS_SLIC_SEGMENTS_DEFAULT = 50
METRICS_SLIC_COMPACTNESS_DEFAULT = 10.0
METRICS_SLIC_SIGMA_DEFAULT = 1.0
METRICS_FAITHFULNESS_STEPS_DEFAULT = 10
METRICS_FAITHFULNESS_BLUR_RADIUS_DEFAULT = 4.0
METRICS_SENSITIVITY_TOP_N_DEFAULT = 10
METRICS_SENSITIVITY_N_RANDOM_DEFAULT = 20
METRICS_SENSITIVITY_BLUR_RADIUS_DEFAULT = 4.0
METRICS_ROBUSTNESS_NOISE_SIGMA_DEFAULT = 0.05
METRICS_ROBUSTNESS_TOPK_FRACS_DEFAULT = (0.1, 0.2)
