from __future__ import annotations

TOP_K = 5
CAM_OVERLAY_ALPHA = 0.45
CAM_SCORE_TYPE_DEFAULT = "logit"
MAX_UI_IMAGE_SIDE = 1024
ANALYSIS_CACHE_TTL_SECONDS = 600
ANALYSIS_CACHE_MAX_ENTRIES = 3

IG_STEPS_DEFAULT = 24
IG_INTERNAL_BATCH_SIZE_DEFAULT = 16
IG_BASELINE_BLUR_RADIUS_DEFAULT = 4

OCC_PATCH_SIZE_DEFAULT = 32
OCC_STRIDE_DEFAULT = 32
OCC_BASELINE_TYPE_DEFAULT = "blur"
OCC_BASELINE_BLUR_RADIUS_DEFAULT = 4

SEMANTIC_CACHE_MAX_ENTRIES = 6
SEMANTIC_CLIP_MODEL_NAME = "ViT-B-32"
SEMANTIC_CLIP_PRETRAINED = "laion2b_s34b_b79k"
SEMANTIC_COMPARE_AGREEMENT_DEFAULT = False
SEMANTIC_SLIC_SEGMENTS_DEFAULT = 80
SEMANTIC_SLIC_COMPACTNESS_DEFAULT = 10.0
SEMANTIC_SLIC_SIGMA_DEFAULT = 1.0
SEMANTIC_TOP_K_SUPERPIXELS_DEFAULT = 10

LIME_N_SAMPLES_DEFAULT = 120
LIME_PERTURBATIONS_PER_EVAL_DEFAULT = 32
LIME_N_SEGMENTS_DEFAULT = 40
LIME_COMPACTNESS_DEFAULT = 10.0
LIME_SIGMA_DEFAULT = 1.0
LIME_BASELINE_BLUR_RADIUS_DEFAULT = 2
LIME_RANDOM_SEED_DEFAULT = 0

METRICS_ENABLED_DEFAULT = True
METRICS_ROBUSTNESS_ENABLED_DEFAULT = False
METRICS_RANDOM_SEED_DEFAULT = 0
METRICS_SLIC_SEGMENTS_DEFAULT = 50
METRICS_SLIC_COMPACTNESS_DEFAULT = 10.0
METRICS_SLIC_SIGMA_DEFAULT = 1.0
METRICS_FAITHFULNESS_STEPS_DEFAULT = 10
METRICS_FAITHFULNESS_BLUR_RADIUS_DEFAULT = 4.0
METRICS_SENSITIVITY_TOP_N_DEFAULT = 10
METRICS_SENSITIVITY_N_RANDOM_DEFAULT = 20
METRICS_SENSITIVITY_BLUR_RADIUS_DEFAULT = 4.0
METRICS_ROBUSTNESS_NOISE_SIGMA_DEFAULT = 0.05
METRICS_ROBUSTNESS_TOPK_FRACS_DEFAULT = (0.1, 0.2)

THESIS_CAM_SCORE_TYPE = "logit"

THESIS_IG_STEPS = 16
THESIS_IG_INTERNAL_BATCH_SIZE = 16
THESIS_IG_BASELINE_BLUR_RADIUS = 4

THESIS_OCC_PATCH_SIZE = 15
THESIS_OCC_STRIDE = 12
THESIS_OCC_BASELINE_TYPE = "zero"
THESIS_OCC_BASELINE_BLUR_RADIUS = 4

THESIS_LIME_N_SAMPLES = 1500
THESIS_LIME_PERTURBATIONS_PER_EVAL = 128
THESIS_LIME_N_SEGMENTS = 140
THESIS_LIME_COMPACTNESS = 12.0
THESIS_LIME_SIGMA = 1.0
THESIS_LIME_BASELINE_BLUR_RADIUS = 2
THESIS_LIME_RANDOM_SEED = 0

THESIS_METRICS_ENABLED = True
THESIS_METRICS_RANDOM_SEED = 0
THESIS_METRICS_SLIC_SEGMENTS = 140
THESIS_METRICS_SLIC_COMPACTNESS = 12.0
THESIS_METRICS_SLIC_SIGMA = 1.0
THESIS_METRICS_FAITHFULNESS_STEPS = 20
THESIS_METRICS_FAITHFULNESS_BLUR_RADIUS = 4.0
THESIS_METRICS_SENSITIVITY_TOP_N = 5
THESIS_METRICS_SENSITIVITY_N_RANDOM = 10
THESIS_METRICS_SENSITIVITY_BLUR_RADIUS = 4.0
THESIS_METRICS_ROBUSTNESS_ENABLED = True
THESIS_METRICS_ROBUSTNESS_NOISE_SIGMA = 0.01
THESIS_METRICS_ROBUSTNESS_TOPK_FRACS = (0.05, 0.1, 0.2)
